// SPDX-License-Identifier: Elastic-2.0
// Copyright (c) 2026 ClaymoreLab
// 由 scripts/build_previz_model_library.mjs 生成，勿手改；改清单去改脚本里的 CATALOG 再重跑。
// 模型取自 Kenney（https://kenney.nl）的 CC0-1.0 素材包，文件在 CDN 上，不进仓库。

export interface PrevizLibraryModel {
  /** 也是名称 key 的末段：`previz.library.model.<id>`。 */
  id: string;
  category: 'furniture' | 'architecture' | 'city' | 'vehicle' | 'prop' | 'nature';
  /** 相对模型库 CDN 根的路径，不带扩展名：`.glb` 是模型，`.webp` 是缩略图。 */
  path: string;
  triangles: number;
  /** 搜索用的英文词。 */
  tags: readonly string[];
}

export const PREVIZ_LIBRARY_MODELS: readonly PrevizLibraryModel[] = [
  { id: 'furniture-chair', category: 'furniture', path: 'furniture/chair', triangles: 170, tags: ['chair'] },
  { id: 'furniture-sofa', category: 'furniture', path: 'furniture/sofa', triangles: 128, tags: ['sofa', 'couch'] },
  { id: 'furniture-dining-table', category: 'furniture', path: 'furniture/dining-table', triangles: 120, tags: ['dining', 'table'] },
  { id: 'furniture-desk', category: 'furniture', path: 'furniture/desk', triangles: 198, tags: ['desk'] },
  { id: 'furniture-bed-double', category: 'furniture', path: 'furniture/bed-double', triangles: 264, tags: ['bed', 'double'] },
  { id: 'furniture-bookshelf', category: 'furniture', path: 'furniture/bookshelf', triangles: 320, tags: ['bookshelf'] },
  { id: 'furniture-nightstand', category: 'furniture', path: 'furniture/nightstand', triangles: 182, tags: ['nightstand'] },
  { id: 'furniture-bar-stool', category: 'furniture', path: 'furniture/bar-stool', triangles: 176, tags: ['bar', 'stool'] },
  { id: 'furniture-floor-lamp', category: 'furniture', path: 'furniture/floor-lamp', triangles: 76, tags: ['floor', 'lamp'] },
  { id: 'furniture-bathtub', category: 'furniture', path: 'furniture/bathtub', triangles: 602, tags: ['bathtub'] },
  { id: 'furniture-armchair', category: 'furniture', path: 'furniture/armchair', triangles: 128, tags: ['armchair'] },
  { id: 'furniture-coffee-table', category: 'furniture', path: 'furniture/coffee-table', triangles: 124, tags: ['coffee', 'table'] },
  { id: 'furniture-console-table', category: 'furniture', path: 'furniture/console-table', triangles: 118, tags: ['console', 'table', 'side table'] },
  { id: 'furniture-bed-single', category: 'furniture', path: 'furniture/bed-single', triangles: 214, tags: ['bed', 'single'] },
  { id: 'furniture-bunk-bed', category: 'furniture', path: 'furniture/bunk-bed', triangles: 580, tags: ['bunk', 'bed'] },
  { id: 'furniture-bookcase-closed', category: 'furniture', path: 'furniture/bookcase-closed', triangles: 296, tags: ['bookcase', 'closed', 'cabinet'] },
  { id: 'furniture-bench', category: 'furniture', path: 'furniture/bench', triangles: 170, tags: ['bench'] },
  { id: 'furniture-office-chair', category: 'furniture', path: 'furniture/office-chair', triangles: 588, tags: ['office', 'chair'] },
  { id: 'furniture-fridge', category: 'furniture', path: 'furniture/fridge', triangles: 250, tags: ['fridge', 'refrigerator'] },
  { id: 'furniture-toilet', category: 'furniture', path: 'furniture/toilet', triangles: 230, tags: ['toilet'] },
  { id: 'furniture-bathroom-cabinet', category: 'furniture', path: 'furniture/bathroom-cabinet', triangles: 64, tags: ['bathroom', 'cabinet'] },
  { id: 'furniture-bathroom-sink', category: 'furniture', path: 'furniture/bathroom-sink', triangles: 316, tags: ['bathroom', 'sink', 'basin'] },
  { id: 'furniture-shower', category: 'furniture', path: 'furniture/shower', triangles: 810, tags: ['shower'] },
  { id: 'furniture-kitchen-cabinet', category: 'furniture', path: 'furniture/kitchen-cabinet', triangles: 114, tags: ['kitchen', 'cabinet'] },
  { id: 'furniture-kitchen-sink', category: 'furniture', path: 'furniture/kitchen-sink', triangles: 318, tags: ['kitchen', 'sink'] },
  { id: 'furniture-stove', category: 'furniture', path: 'furniture/stove', triangles: 830, tags: ['stove', 'cooker', 'oven'] },
  { id: 'furniture-kitchen-bar', category: 'furniture', path: 'furniture/kitchen-bar', triangles: 76, tags: ['kitchen', 'bar', 'counter'] },
  { id: 'furniture-hexagonal-table', category: 'furniture', path: 'furniture/hexagonal-table', triangles: 80, tags: ['hexagonal', 'table'] },
  { id: 'furniture-glass-table', category: 'furniture', path: 'furniture/glass-table', triangles: 144, tags: ['glass', 'table'] },
  { id: 'furniture-lounge-chair', category: 'furniture', path: 'furniture/lounge-chair', triangles: 188, tags: ['lounge', 'chair', 'recliner'] },
  { id: 'furniture-design-sofa', category: 'furniture', path: 'furniture/design-sofa', triangles: 116, tags: ['design', 'sofa', 'couch'] },
  { id: 'furniture-ottoman', category: 'furniture', path: 'furniture/ottoman', triangles: 84, tags: ['ottoman', 'footstool'] },
  { id: 'furniture-cushion-chair', category: 'furniture', path: 'furniture/cushion-chair', triangles: 198, tags: ['cushion', 'chair'] },
  { id: 'furniture-modern-chair', category: 'furniture', path: 'furniture/modern-chair', triangles: 92, tags: ['modern', 'chair'] },
  { id: 'furniture-table-lamp', category: 'furniture', path: 'furniture/table-lamp', triangles: 76, tags: ['table', 'lamp'] },
  { id: 'furniture-wall-lamp', category: 'furniture', path: 'furniture/wall-lamp', triangles: 42, tags: ['wall', 'lamp', 'sconce'] },
  { id: 'furniture-ceiling-lamp', category: 'furniture', path: 'furniture/ceiling-lamp', triangles: 60, tags: ['ceiling', 'lamp', 'pendant'] },
  { id: 'furniture-rug', category: 'furniture', path: 'furniture/rug', triangles: 28, tags: ['rug', 'carpet'] },
  { id: 'furniture-tv-cabinet', category: 'furniture', path: 'furniture/tv-cabinet', triangles: 154, tags: ['tv', 'cabinet'] },
  { id: 'furniture-loveseat', category: 'furniture', path: 'furniture/loveseat', triangles: 116, tags: ['loveseat', 'couch', 'sofa'] },
  { id: 'architecture-wall', category: 'architecture', path: 'architecture/wall', triangles: 10, tags: ['wall'] },
  { id: 'architecture-wall-half', category: 'architecture', path: 'architecture/wall-half', triangles: 10, tags: ['wall', 'half'] },
  { id: 'architecture-wall-low', category: 'architecture', path: 'architecture/wall-low', triangles: 10, tags: ['wall', 'low'] },
  { id: 'architecture-wall-corner', category: 'architecture', path: 'architecture/wall-corner', triangles: 16, tags: ['wall', 'corner'] },
  { id: 'architecture-wall-corner-diagonal', category: 'architecture', path: 'architecture/wall-corner-diagonal', triangles: 22, tags: ['wall', 'corner', 'diagonal'] },
  { id: 'architecture-wall-corner-round', category: 'architecture', path: 'architecture/wall-corner-round', triangles: 76, tags: ['wall', 'corner', 'round'] },
  { id: 'architecture-doorway', category: 'architecture', path: 'architecture/doorway', triangles: 64, tags: ['doorway'] },
  { id: 'architecture-doorway-arch', category: 'architecture', path: 'architecture/doorway-arch', triangles: 164, tags: ['doorway', 'arch'] },
  { id: 'architecture-doorway-wide', category: 'architecture', path: 'architecture/doorway-wide', triangles: 64, tags: ['doorway', 'wide', 'garage'] },
  { id: 'architecture-doorway-wide-arch', category: 'architecture', path: 'architecture/doorway-wide-arch', triangles: 176, tags: ['doorway', 'wide', 'arch'] },
  { id: 'architecture-window-wall', category: 'architecture', path: 'architecture/window-wall', triangles: 98, tags: ['window', 'wall'] },
  { id: 'architecture-window-wall-wide', category: 'architecture', path: 'architecture/window-wall-wide', triangles: 98, tags: ['window', 'wall', 'wide'] },
  { id: 'architecture-window-wall-arch', category: 'architecture', path: 'architecture/window-wall-arch', triangles: 216, tags: ['window', 'wall', 'arch'] },
  { id: 'architecture-door', category: 'architecture', path: 'architecture/door', triangles: 188, tags: ['door'] },
  { id: 'architecture-door-arch', category: 'architecture', path: 'architecture/door-arch', triangles: 172, tags: ['door', 'arch'] },
  { id: 'architecture-floor', category: 'architecture', path: 'architecture/floor', triangles: 12, tags: ['floor'] },
  { id: 'architecture-floor-half', category: 'architecture', path: 'architecture/floor-half', triangles: 12, tags: ['floor', 'half'] },
  { id: 'architecture-column', category: 'architecture', path: 'architecture/column', triangles: 38, tags: ['column', 'pillar'] },
  { id: 'architecture-column-wide', category: 'architecture', path: 'architecture/column-wide', triangles: 38, tags: ['column', 'wide', 'pillar'] },
  { id: 'architecture-stairs', category: 'architecture', path: 'architecture/stairs', triangles: 148, tags: ['stairs', 'steps'] },
  { id: 'architecture-stairs-open', category: 'architecture', path: 'architecture/stairs-open', triangles: 132, tags: ['stairs', 'open', 'steps'] },
  { id: 'architecture-stairs-short', category: 'architecture', path: 'architecture/stairs-short', triangles: 76, tags: ['stairs', 'short', 'steps'] },
  { id: 'architecture-stairs-narrow', category: 'architecture', path: 'architecture/stairs-narrow', triangles: 114, tags: ['stairs', 'narrow', 'steps'] },
  { id: 'architecture-roof-flat', category: 'architecture', path: 'architecture/roof-flat', triangles: 84, tags: ['roof', 'flat'] },
  { id: 'city-building-a', category: 'city', path: 'city/building-a', triangles: 1252, tags: ['building', 'a'] },
  { id: 'city-building-c', category: 'city', path: 'city/building-c', triangles: 1195, tags: ['building', 'c'] },
  { id: 'city-building-f', category: 'city', path: 'city/building-f', triangles: 1794, tags: ['building', 'f'] },
  { id: 'city-building-h', category: 'city', path: 'city/building-h', triangles: 1512, tags: ['building', 'h'] },
  { id: 'city-skyscraper-a', category: 'city', path: 'city/skyscraper-a', triangles: 1292, tags: ['skyscraper', 'a', 'tower'] },
  { id: 'city-skyscraper-c', category: 'city', path: 'city/skyscraper-c', triangles: 1704, tags: ['skyscraper', 'c', 'tower'] },
  { id: 'city-house-a', category: 'city', path: 'city/house-a', triangles: 1174, tags: ['house', 'a', 'home'] },
  { id: 'city-house-f', category: 'city', path: 'city/house-f', triangles: 1616, tags: ['house', 'f', 'home'] },
  { id: 'city-house-k', category: 'city', path: 'city/house-k', triangles: 1024, tags: ['house', 'k', 'home'] },
  { id: 'city-factory-a', category: 'city', path: 'city/factory-a', triangles: 2046, tags: ['factory', 'a', 'industrial'] },
  { id: 'city-factory-d', category: 'city', path: 'city/factory-d', triangles: 1158, tags: ['factory', 'd', 'industrial'] },
  { id: 'city-road', category: 'city', path: 'city/road', triangles: 44, tags: ['road', 'street'] },
  { id: 'city-crosswalk', category: 'city', path: 'city/crosswalk', triangles: 104, tags: ['crosswalk', 'crossing', 'zebra'] },
  { id: 'city-road-bend', category: 'city', path: 'city/road-bend', triangles: 260, tags: ['road', 'bend', 'street'] },
  { id: 'city-road-curve', category: 'city', path: 'city/road-curve', triangles: 308, tags: ['road', 'curve', 'street'] },
  { id: 'city-crossroad', category: 'city', path: 'city/crossroad', triangles: 116, tags: ['crossroad', 'intersection'] },
  { id: 'city-t-junction', category: 'city', path: 'city/t-junction', triangles: 84, tags: ['t', 'junction', 'intersection'] },
  { id: 'city-roundabout', category: 'city', path: 'city/roundabout', triangles: 1636, tags: ['roundabout'] },
  { id: 'city-road-end', category: 'city', path: 'city/road-end', triangles: 218, tags: ['road', 'end', 'street'] },
  { id: 'city-road-barrier', category: 'city', path: 'city/road-barrier', triangles: 24, tags: ['road', 'barrier', 'guardrail'] },
  { id: 'city-road-side', category: 'city', path: 'city/road-side', triangles: 44, tags: ['road', 'side'] },
  { id: 'city-sidewalk-corner', category: 'city', path: 'city/sidewalk-corner', triangles: 220, tags: ['sidewalk', 'corner'] },
  { id: 'city-road-bridge', category: 'city', path: 'city/road-bridge', triangles: 240, tags: ['road', 'bridge'] },
  { id: 'city-bridge-pillar', category: 'city', path: 'city/bridge-pillar', triangles: 38, tags: ['bridge', 'pillar'] },
  { id: 'city-bridge-pillar-wide', category: 'city', path: 'city/bridge-pillar-wide', triangles: 38, tags: ['bridge', 'pillar', 'wide'] },
  { id: 'city-street-light', category: 'city', path: 'city/street-light', triangles: 92, tags: ['street', 'light', 'lamp'] },
  { id: 'city-street-light-double', category: 'city', path: 'city/street-light-double', triangles: 152, tags: ['street', 'light', 'double', 'lamp'] },
  { id: 'city-street-light-square', category: 'city', path: 'city/street-light-square', triangles: 60, tags: ['street', 'light', 'square', 'lamp'] },
  { id: 'city-street-light-square-double', category: 'city', path: 'city/street-light-square-double', triangles: 88, tags: ['street', 'light', 'square', 'double', 'lamp'] },
  { id: 'city-traffic-light', category: 'city', path: 'city/traffic-light', triangles: 212, tags: ['traffic', 'light'] },
  { id: 'city-traffic-light-hanging', category: 'city', path: 'city/traffic-light-hanging', triangles: 230, tags: ['traffic', 'light', 'hanging'] },
  { id: 'city-stop-sign', category: 'city', path: 'city/stop-sign', triangles: 104, tags: ['stop', 'sign'] },
  { id: 'city-warning-sign', category: 'city', path: 'city/warning-sign', triangles: 104, tags: ['warning', 'sign'] },
  { id: 'city-street-sign', category: 'city', path: 'city/street-sign', triangles: 154, tags: ['street', 'sign'] },
  { id: 'city-highway-sign', category: 'city', path: 'city/highway-sign', triangles: 180, tags: ['highway', 'sign'] },
  { id: 'city-highway-sign-wide', category: 'city', path: 'city/highway-sign-wide', triangles: 144, tags: ['highway', 'sign', 'wide'] },
  { id: 'city-construction-barrier', category: 'city', path: 'city/construction-barrier', triangles: 60, tags: ['construction', 'barrier'] },
  { id: 'city-construction-fence', category: 'city', path: 'city/construction-fence', triangles: 136, tags: ['construction', 'fence'] },
  { id: 'city-construction-light', category: 'city', path: 'city/construction-light', triangles: 144, tags: ['construction', 'light'] },
  { id: 'city-dumpster', category: 'city', path: 'city/dumpster', triangles: 234, tags: ['dumpster', 'trash', 'bin'] },
  { id: 'city-power-pole', category: 'city', path: 'city/power-pole', triangles: 416, tags: ['power', 'pole', 'utility pole'] },
  { id: 'city-power-pole-wide', category: 'city', path: 'city/power-pole-wide', triangles: 544, tags: ['power', 'pole', 'wide', 'utility pole'] },
  { id: 'city-power-lines', category: 'city', path: 'city/power-lines', triangles: 72, tags: ['power', 'lines', 'wires'] },
  { id: 'city-parasol', category: 'city', path: 'city/parasol', triangles: 96, tags: ['parasol', 'umbrella'] },
  { id: 'city-awning', category: 'city', path: 'city/awning', triangles: 40, tags: ['awning'] },
  { id: 'city-fence', category: 'city', path: 'city/fence', triangles: 88, tags: ['fence'] },
  { id: 'city-fence-low', category: 'city', path: 'city/fence-low', triangles: 180, tags: ['fence', 'low'] },
  { id: 'city-fence-long', category: 'city', path: 'city/fence-long', triangles: 252, tags: ['fence', 'long'] },
  { id: 'city-fence-wide', category: 'city', path: 'city/fence-wide', triangles: 364, tags: ['fence', 'wide'] },
  { id: 'city-driveway-long', category: 'city', path: 'city/driveway-long', triangles: 12, tags: ['driveway', 'long'] },
  { id: 'city-driveway-short', category: 'city', path: 'city/driveway-short', triangles: 12, tags: ['driveway', 'short'] },
  { id: 'city-path-long', category: 'city', path: 'city/path-long', triangles: 12, tags: ['path', 'long', 'walkway'] },
  { id: 'city-path-short', category: 'city', path: 'city/path-short', triangles: 12, tags: ['path', 'short', 'walkway'] },
  { id: 'city-path-stones', category: 'city', path: 'city/path-stones', triangles: 48, tags: ['path', 'stones'] },
  { id: 'city-planter', category: 'city', path: 'city/planter', triangles: 204, tags: ['planter'] },
  { id: 'city-chimney-large', category: 'city', path: 'city/chimney-large', triangles: 218, tags: ['chimney', 'large', 'smokestack'] },
  { id: 'city-chimney-medium', category: 'city', path: 'city/chimney-medium', triangles: 160, tags: ['chimney', 'medium', 'smokestack'] },
  { id: 'city-tank', category: 'city', path: 'city/tank', triangles: 310, tags: ['tank'] },
  { id: 'city-water-tower', category: 'city', path: 'city/water-tower', triangles: 968, tags: ['water', 'tower'] },
  { id: 'city-shipping-container', category: 'city', path: 'city/shipping-container', triangles: 402, tags: ['shipping', 'container'] },
  { id: 'vehicle-sedan', category: 'vehicle', path: 'vehicle/sedan', triangles: 2032, tags: ['sedan', 'car'] },
  { id: 'vehicle-truck', category: 'vehicle', path: 'vehicle/truck', triangles: 2082, tags: ['truck', 'lorry'] },
  { id: 'vehicle-taxi', category: 'vehicle', path: 'vehicle/taxi', triangles: 2072, tags: ['taxi', 'cab', 'car'] },
  { id: 'vehicle-police', category: 'vehicle', path: 'vehicle/police', triangles: 2304, tags: ['police', 'car'] },
  { id: 'vehicle-ambulance', category: 'vehicle', path: 'vehicle/ambulance', triangles: 2804, tags: ['ambulance'] },
  { id: 'vehicle-firetruck', category: 'vehicle', path: 'vehicle/firetruck', triangles: 2767, tags: ['firetruck'] },
  { id: 'vehicle-van', category: 'vehicle', path: 'vehicle/van', triangles: 2082, tags: ['van'] },
  { id: 'vehicle-delivery', category: 'vehicle', path: 'vehicle/delivery', triangles: 2476, tags: ['delivery'] },
  { id: 'vehicle-suv', category: 'vehicle', path: 'vehicle/suv', triangles: 2474, tags: ['suv', 'car'] },
  { id: 'vehicle-sports-car', category: 'vehicle', path: 'vehicle/sports-car', triangles: 2088, tags: ['sports', 'car'] },
  { id: 'vehicle-hatchback', category: 'vehicle', path: 'vehicle/hatchback', triangles: 2088, tags: ['hatchback', 'car'] },
  { id: 'vehicle-tractor', category: 'vehicle', path: 'vehicle/tractor', triangles: 2044, tags: ['tractor'] },
  { id: 'vehicle-garbage-truck', category: 'vehicle', path: 'vehicle/garbage-truck', triangles: 3124, tags: ['garbage', 'truck'] },
  { id: 'vehicle-race-car', category: 'vehicle', path: 'vehicle/race-car', triangles: 1952, tags: ['race', 'car'] },
  { id: 'vehicle-suv-luxury', category: 'vehicle', path: 'vehicle/suv-luxury', triangles: 2086, tags: ['suv', 'luxury', 'car'] },
  { id: 'vehicle-flatbed-truck', category: 'vehicle', path: 'vehicle/flatbed-truck', triangles: 2488, tags: ['flatbed', 'truck'] },
  { id: 'vehicle-loader', category: 'vehicle', path: 'vehicle/loader', triangles: 2646, tags: ['loader', 'bulldozer'] },
  { id: 'vehicle-race-car-future', category: 'vehicle', path: 'vehicle/race-car-future', triangles: 2068, tags: ['race', 'car', 'future'] },
  { id: 'vehicle-kart', category: 'vehicle', path: 'vehicle/kart', triangles: 2884, tags: ['kart', 'go-kart'] },
  { id: 'vehicle-canoe', category: 'vehicle', path: 'vehicle/canoe', triangles: 200, tags: ['canoe', 'boat'] },
  { id: 'prop-crate', category: 'prop', path: 'prop/crate', triangles: 124, tags: ['crate', 'box'] },
  { id: 'prop-monitor', category: 'prop', path: 'prop/monitor', triangles: 72, tags: ['monitor', 'screen'] },
  { id: 'prop-cardboard-box', category: 'prop', path: 'prop/cardboard-box', triangles: 60, tags: ['cardboard', 'box'] },
  { id: 'prop-cardboard-box-open', category: 'prop', path: 'prop/cardboard-box-open', triangles: 60, tags: ['cardboard', 'box', 'open'] },
  { id: 'prop-laptop', category: 'prop', path: 'prop/laptop', triangles: 68, tags: ['laptop'] },
  { id: 'prop-television', category: 'prop', path: 'prop/television', triangles: 72, tags: ['television', 'tv'] },
  { id: 'prop-television-vintage', category: 'prop', path: 'prop/television-vintage', triangles: 280, tags: ['television', 'vintage', 'tv'] },
  { id: 'prop-radio', category: 'prop', path: 'prop/radio', triangles: 432, tags: ['radio'] },
  { id: 'prop-books', category: 'prop', path: 'prop/books', triangles: 62, tags: ['books'] },
  { id: 'prop-keyboard', category: 'prop', path: 'prop/keyboard', triangles: 32, tags: ['keyboard'] },
  { id: 'prop-mouse', category: 'prop', path: 'prop/mouse', triangles: 71, tags: ['mouse'] },
  { id: 'prop-speaker', category: 'prop', path: 'prop/speaker', triangles: 228, tags: ['speaker'] },
  { id: 'prop-toaster', category: 'prop', path: 'prop/toaster', triangles: 220, tags: ['toaster'] },
  { id: 'prop-coffee-machine', category: 'prop', path: 'prop/coffee-machine', triangles: 166, tags: ['coffee', 'machine'] },
  { id: 'prop-microwave', category: 'prop', path: 'prop/microwave', triangles: 152, tags: ['microwave'] },
  { id: 'prop-blender', category: 'prop', path: 'prop/blender', triangles: 246, tags: ['blender'] },
  { id: 'prop-pillow', category: 'prop', path: 'prop/pillow', triangles: 50, tags: ['pillow', 'cushion'] },
  { id: 'prop-mirror', category: 'prop', path: 'prop/mirror', triangles: 72, tags: ['mirror'] },
  { id: 'prop-ceiling-fan', category: 'prop', path: 'prop/ceiling-fan', triangles: 214, tags: ['ceiling', 'fan'] },
  { id: 'prop-coat-rack', category: 'prop', path: 'prop/coat-rack', triangles: 190, tags: ['coat', 'rack'] },
  { id: 'prop-teddy-bear', category: 'prop', path: 'prop/teddy-bear', triangles: 134, tags: ['teddy', 'bear', 'toy'] },
  { id: 'prop-potted-plant', category: 'prop', path: 'prop/potted-plant', triangles: 60, tags: ['potted', 'plant'] },
  { id: 'prop-trash-can', category: 'prop', path: 'prop/trash-can', triangles: 68, tags: ['trash', 'can', 'bin'] },
  { id: 'prop-washing-machine', category: 'prop', path: 'prop/washing-machine', triangles: 720, tags: ['washing', 'machine'] },
  { id: 'prop-traffic-cone', category: 'prop', path: 'prop/traffic-cone', triangles: 66, tags: ['traffic', 'cone'] },
  { id: 'prop-tent-closed', category: 'prop', path: 'prop/tent-closed', triangles: 228, tags: ['tent', 'closed'] },
  { id: 'prop-tent-open', category: 'prop', path: 'prop/tent-open', triangles: 232, tags: ['tent', 'open'] },
  { id: 'prop-campfire-stones', category: 'prop', path: 'prop/campfire-stones', triangles: 264, tags: ['campfire', 'stones'] },
  { id: 'prop-campfire-logs', category: 'prop', path: 'prop/campfire-logs', triangles: 112, tags: ['campfire', 'logs'] },
  { id: 'prop-paddle', category: 'prop', path: 'prop/paddle', triangles: 32, tags: ['paddle', 'oar'] },
  { id: 'prop-barrel', category: 'prop', path: 'prop/barrel', triangles: 412, tags: ['barrel'] },
  { id: 'prop-chest', category: 'prop', path: 'prop/chest', triangles: 322, tags: ['chest', 'treasure'] },
  { id: 'prop-bucket', category: 'prop', path: 'prop/bucket', triangles: 68, tags: ['bucket'] },
  { id: 'prop-axe', category: 'prop', path: 'prop/axe', triangles: 84, tags: ['axe', 'tool'] },
  { id: 'prop-shovel', category: 'prop', path: 'prop/shovel', triangles: 124, tags: ['shovel', 'tool'] },
  { id: 'prop-hammer', category: 'prop', path: 'prop/hammer', triangles: 52, tags: ['hammer', 'tool'] },
  { id: 'prop-pickaxe', category: 'prop', path: 'prop/pickaxe', triangles: 74, tags: ['pickaxe', 'tool'] },
  { id: 'prop-workbench', category: 'prop', path: 'prop/workbench', triangles: 236, tags: ['workbench'] },
  { id: 'prop-signpost', category: 'prop', path: 'prop/signpost', triangles: 44, tags: ['signpost'] },
  { id: 'nature-bush', category: 'nature', path: 'nature/bush', triangles: 32, tags: ['bush', 'shrub'] },
  { id: 'nature-bush-small', category: 'nature', path: 'nature/bush-small', triangles: 16, tags: ['bush', 'small', 'shrub'] },
  { id: 'nature-bush-large', category: 'nature', path: 'nature/bush-large', triangles: 60, tags: ['bush', 'large', 'shrub'] },
  { id: 'nature-bush-triangle', category: 'nature', path: 'nature/bush-triangle', triangles: 30, tags: ['bush', 'triangle', 'shrub'] },
  { id: 'nature-bush-triangle-large', category: 'nature', path: 'nature/bush-triangle-large', triangles: 39, tags: ['bush', 'triangle', 'large', 'shrub'] },
  { id: 'nature-tree-oak', category: 'nature', path: 'nature/tree-oak', triangles: 196, tags: ['tree', 'oak'] },
  { id: 'nature-tree-default', category: 'nature', path: 'nature/tree-default', triangles: 114, tags: ['tree', 'default'] },
  { id: 'nature-tree-fat', category: 'nature', path: 'nature/tree-fat', triangles: 50, tags: ['tree', 'fat'] },
  { id: 'nature-tree-blocks', category: 'nature', path: 'nature/tree-blocks', triangles: 132, tags: ['tree', 'blocks'] },
  { id: 'nature-tree-cone', category: 'nature', path: 'nature/tree-cone', triangles: 132, tags: ['tree', 'cone'] },
  { id: 'nature-tree-pine', category: 'nature', path: 'nature/tree-pine', triangles: 230, tags: ['tree', 'pine'] },
  { id: 'nature-tree-pine-tall', category: 'nature', path: 'nature/tree-pine-tall', triangles: 134, tags: ['tree', 'pine', 'tall'] },
  { id: 'nature-tree-pine-small', category: 'nature', path: 'nature/tree-pine-small', triangles: 164, tags: ['tree', 'pine', 'small'] },
  { id: 'nature-tree-fir', category: 'nature', path: 'nature/tree-fir', triangles: 204, tags: ['tree', 'fir'] },
  { id: 'nature-tree-palm', category: 'nature', path: 'nature/tree-palm', triangles: 186, tags: ['tree', 'palm'] },
  { id: 'nature-tree-palm-bend', category: 'nature', path: 'nature/tree-palm-bend', triangles: 200, tags: ['tree', 'palm', 'bend'] },
  { id: 'nature-tree-palm-detailed', category: 'nature', path: 'nature/tree-palm-detailed', triangles: 336, tags: ['tree', 'palm', 'detailed'] },
  { id: 'nature-tree-suburban-large', category: 'nature', path: 'nature/tree-suburban-large', triangles: 42, tags: ['tree', 'suburban', 'large'] },
  { id: 'nature-tree-suburban-small', category: 'nature', path: 'nature/tree-suburban-small', triangles: 42, tags: ['tree', 'suburban', 'small'] },
  { id: 'nature-grass', category: 'nature', path: 'nature/grass', triangles: 132, tags: ['grass'] },
  { id: 'nature-grass-leafy', category: 'nature', path: 'nature/grass-leafy', triangles: 144, tags: ['grass', 'leafy'] },
  { id: 'nature-reeds', category: 'nature', path: 'nature/reeds', triangles: 32, tags: ['reeds'] },
  { id: 'nature-flower-red', category: 'nature', path: 'nature/flower-red', triangles: 76, tags: ['flower', 'red'] },
  { id: 'nature-flower-yellow', category: 'nature', path: 'nature/flower-yellow', triangles: 76, tags: ['flower', 'yellow'] },
  { id: 'nature-flower-purple', category: 'nature', path: 'nature/flower-purple', triangles: 76, tags: ['flower', 'purple'] },
  { id: 'nature-mushroom', category: 'nature', path: 'nature/mushroom', triangles: 48, tags: ['mushroom'] },
  { id: 'nature-mushroom-tall', category: 'nature', path: 'nature/mushroom-tall', triangles: 48, tags: ['mushroom', 'tall'] },
  { id: 'nature-cactus', category: 'nature', path: 'nature/cactus', triangles: 122, tags: ['cactus'] },
  { id: 'nature-cactus-short', category: 'nature', path: 'nature/cactus-short', triangles: 116, tags: ['cactus', 'short'] },
  { id: 'nature-boulder', category: 'nature', path: 'nature/boulder', triangles: 80, tags: ['boulder', 'rock'] },
  { id: 'nature-rock-tall', category: 'nature', path: 'nature/rock-tall', triangles: 136, tags: ['rock', 'tall'] },
  { id: 'nature-rock-flat', category: 'nature', path: 'nature/rock-flat', triangles: 20, tags: ['rock', 'flat', 'stone'] },
  { id: 'nature-pebbles', category: 'nature', path: 'nature/pebbles', triangles: 16, tags: ['pebbles', 'stone', 'rock'] },
  { id: 'nature-cliff', category: 'nature', path: 'nature/cliff', triangles: 12, tags: ['cliff', 'rock'] },
  { id: 'nature-stump', category: 'nature', path: 'nature/stump', triangles: 56, tags: ['stump'] },
  { id: 'nature-stump-detailed', category: 'nature', path: 'nature/stump-detailed', triangles: 96, tags: ['stump', 'detailed'] },
  { id: 'nature-log', category: 'nature', path: 'nature/log', triangles: 200, tags: ['log'] },
  { id: 'nature-log-stack', category: 'nature', path: 'nature/log-stack', triangles: 184, tags: ['log', 'stack'] },
  { id: 'nature-log-stack-large', category: 'nature', path: 'nature/log-stack-large', triangles: 310, tags: ['log', 'stack', 'large'] },
];
