# Generated by scripts/sync_interactive_story_tools.py; edit the source file.
"""Bounded API error diagnostics shared by agent tool hosts (stdlib only)."""

from __future__ import annotations

import json
import re
from typing import Any


def _maybe_json(text: str) -> Any:
    stripped = text.strip()
    if not stripped:
        return None
    try:
        return json.loads(stripped)
    except json.JSONDecodeError:
        return stripped


def _safe_error_string(value: Any, limit: int) -> str:
    if not isinstance(value, str):
        return ""
    cleaned = " ".join(value.split())[:limit]
    if re.search(
        r"traceback|authorization|bearer\s|api[_-]?key|secret|password", cleaned, re.I
    ):
        return ""
    return cleaned


def _http_error_result(status_code: int, text: str, reason: str) -> dict[str, Any]:
    """Expose only bounded validation diagnostics from the project API."""
    result: dict[str, Any] = {
        "ok": False,
        "status": "failed",
        "status_code": status_code,
        "error": _safe_error_string(reason, 300) or "HTTP request failed",
    }
    if len(text) > 65536:
        return result
    data = _maybe_json(text)
    if 500 <= status_code < 600:
        if isinstance(data, dict):
            for field in ("error", "message", "detail"):
                value = _safe_error_string(data.get(field), 300)
                if value:
                    result["error"] = value
                    break
        elif isinstance(data, str) and not data.lstrip().startswith("<"):
            result["error"] = _safe_error_string(data, 300) or result["error"]
        return result
    if not 400 <= status_code < 500:
        return result
    if not isinstance(data, dict):
        return result
    detail = data.get("detail")
    source = detail if isinstance(detail, dict) else data
    for field in ("status", "code", "next_action"):
        value = _safe_error_string(source.get(field), 80)
        if value and re.fullmatch(r"[A-Za-z0-9_.-]+", value):
            result[field] = value
    for field in ("error", "message"):
        value = _safe_error_string(source.get(field), 300)
        if value:
            result[field] = value
    if result.get("code") in {"revision_conflict", "canvas_revision_conflict"}:
        revision = source.get("current_revision")
        if type(revision) is int and revision >= 0:
            result["current_revision"] = revision
        if result.get("code") == "revision_conflict":
            story_id = _safe_error_string(source.get("story_id"), 128)
            if story_id and re.fullmatch(r"[A-Za-z0-9_.:-]+", story_id):
                result["story_id"] = story_id
    if isinstance(detail, str):
        result["error"] = _safe_error_string(detail, 300) or result["error"]
    if isinstance(source.get("retryable"), bool):
        result["retryable"] = source["retryable"]
    if result.get("code") == "generation_parameters_required":
        # Bounded copy of the standard clarification request so the agent can
        # answer it; anything malformed is dropped rather than forwarded.
        missing = source.get("missing_parameters")
        safe_missing: list[dict[str, Any]] = []
        if isinstance(missing, list):
            for item in missing[:50]:
                if not isinstance(item, dict):
                    continue
                node_type = _safe_error_string(item.get("node_type"), 40)
                node_id = _safe_error_string(item.get("node_id"), 160)
                fields = item.get("fields")
                if node_type not in {"imageGenNode", "videoNode"} or not isinstance(
                    fields, list
                ):
                    continue
                safe_fields = [
                    value
                    for value in (
                        _safe_error_string(field, 40) for field in fields[:12]
                    )
                    if value and re.fullmatch(r"[A-Za-z0-9_]+", value)
                ]
                if node_id and safe_fields:
                    safe_missing.append(
                        {
                            "node_id": node_id,
                            "node_type": node_type,
                            "fields": safe_fields,
                        }
                    )
        if safe_missing:
            result["missing_parameters"] = safe_missing
    errors = source.get("errors")
    if isinstance(errors, list):
        safe_errors = []
        for item in errors[:5]:
            if not isinstance(item, dict):
                continue
            path = _safe_error_string(item.get("path"), 160)
            if (
                not path
                and type(item.get("index")) is int
                and 0 <= item["index"] <= 9999
            ):
                path = f"edges[{item['index']}]"
            message = _safe_error_string(item.get("message") or item.get("reason"), 240)
            if not path or not re.fullmatch(r"[A-Za-z0-9_.\[\]-]+", path):
                continue
            safe_errors.append(
                {"path": path, **({"message": message} if message else {})}
            )
        if safe_errors:
            result["errors"] = safe_errors
    while len(
        json.dumps(result, ensure_ascii=False).encode("utf-8")
    ) > 4096 and result.get("errors"):
        result["errors"].pop()
    return result
