#!/usr/bin/env python3
"""Bundle stdlib agent definitions for Hermes without application imports."""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BUNDLES = {
    "src/novelvideo/chat/story_tools.py": ".hermes/plugins/dramaclaw/interactive_story.py",
    "src/novelvideo/chat/agent_api_errors.py": ".hermes/plugins/freezone/_agent_api_errors.py",
}
HEADER = "# Generated by scripts/sync_interactive_story_tools.py; edit the source file.\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    check = parser.parse_args().check
    stale = []
    for source, destination in BUNDLES.items():
        expected = HEADER + (ROOT / source).read_text(encoding="utf-8")
        target = ROOT / destination
        if check:
            if not target.is_file() or target.read_text(encoding="utf-8") != expected:
                stale.append(destination)
        else:
            target.write_text(expected, encoding="utf-8")
    if stale:
        print("Stale Hermes tool bundles: " + ", ".join(stale))
        print("Run python scripts/sync_interactive_story_tools.py")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
